# Use the official Docker Hub PostgreSQL 13 image
FROM postgres:13

# Set environment variables - replace with your own values
ENV POSTGRES_DB=iexdb
ENV POSTGRES_USER=iexuser
ENV POSTGRES_PASSWORD=iexpass